export const POSTS = [
  {
    slug: 'how-to-write-sales-resume',
    tag: 'Job Search Tips', tagColor: '#0C63E3', tagBg: '#EEF4FF',
    title: 'How to Write a Sales Resume That Gets Interviews (Examples + Templates)',
    excerpt: 'Learn how to write a winning sales resume with examples, templates, and tips to showcase your achievements.',
    author: 'Sarah Johnson', authorInitials: 'SJ',
    date: 'Mar 20, 2026', read: '8 min',
    image: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: true,
    body: [
      { type: 'p', text: 'A strong sales resume isn\'t just a list of your quota numbers. It\'s a story of how you moved people — from cold to curious, from skeptical to signed. Yet most sales resumes look identical: a pile of percentages and titles with no context.' },
      { type: 'h2', text: 'Lead with your most impressive number' },
      { type: 'p', text: 'Hiring managers for sales roles spend an average of 6 seconds scanning your resume before deciding whether to keep reading. That means your single most impressive achievement needs to be visible in the top third of the page.' },
      { type: 'p', text: 'Don\'t bury "exceeded quota by 147% in Q3" three bullet points down. Put it front and center in your professional summary or make it the first bullet under your most recent role.' },
      { type: 'callout', text: 'Pro tip: Always include the time period for your results. "Closed $2.1M in ARR" is good. "Closed $2.1M in ARR in my first 9 months" is unforgettable.' },
      { type: 'h2', text: 'Use the CAR framework for every bullet point' },
      { type: 'p', text: 'Context, Action, Result. Every bullet point on your resume should answer these three questions. Context: what was the situation? Action: what did you specifically do? Result: what happened because of it?' },
      { type: 'p', text: '"Managed accounts" tells a hiring manager nothing. "Inherited a book of 42 at-risk accounts, rebuilt relationships through weekly QBRs, and reduced churn by 31% in two quarters" tells a story.' },
      { type: 'h2', text: 'Tailor your resume for the role, not the industry' },
      { type: 'p', text: 'There is no universal sales resume. An enterprise AE resume should look completely different from an SDR resume. The skills, metrics, and language that matter are different — and experienced hiring managers will notice immediately if yours doesn\'t match the level they\'re hiring for.' },
      { type: 'p', text: 'Read the job description carefully. Mirror their language. If they say "territory management," use that phrase. If they mention specific tools, make sure yours are visible.' },
      { type: 'h2', text: 'Add a video resume to separate yourself entirely' },
      { type: 'p', text: 'Here\'s the thing about sales hiring: your resume proves you can write. But your job is to sell. A video resume gives you the chance to demonstrate the one thing no PDF ever can — your actual ability to connect, communicate, and build rapport.' },
      { type: 'p', text: 'Candidates who add a Reslink to their application see 3× more recruiter callbacks than those who submit PDF-only. In a competitive sales market, that\'s the edge that gets you the interview.' },
    ],
  },
  {
    slug: 'how-long-should-resume-be',
    tag: 'Job Search Tips', tagColor: '#0C63E3', tagBg: '#EEF4FF',
    title: 'How Long Should a Resume Be? The Complete Guide for Job Seekers',
    excerpt: 'Learn how long a resume should be, from entry-level to executive roles, with tips, examples, and best practices.',
    author: 'Michael Chen', authorInitials: 'MC',
    date: 'Mar 18, 2026', read: '5 min',
    image: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: false,
    body: [
      { type: 'p', text: 'One page. Two pages. No more than this. Never more than that. Resume length advice is everywhere, and most of it contradicts itself. Here\'s the actual answer: it depends on your experience level, and the rule is simpler than you think.' },
      { type: 'h2', text: 'Entry-level and recent graduates: one page, always' },
      { type: 'p', text: 'If you have less than 3 years of relevant work experience, your resume should be one page. Full stop. You don\'t have enough signal to justify two pages, and trying to fill them forces you to pad your content with fluff that hurts more than it helps.' },
      { type: 'p', text: 'Focus on what actually matters: your most relevant experiences, measurable outcomes where possible, and skills that map directly to the job description.' },
      { type: 'callout', text: 'The test: If removing a bullet point wouldn\'t change a hiring manager\'s opinion of you, delete it.' },
      { type: 'h2', text: 'Mid-career professionals: one to two pages' },
      { type: 'p', text: 'If you have 3–10 years of experience, you have permission to go to two pages — but only if you\'re using every inch of that space to tell a compelling story. White space, repetitive bullets, and obvious filler are red flags that suggest poor judgment.' },
      { type: 'h2', text: 'Senior and executive professionals: two pages max' },
      { type: 'p', text: 'Even if you have 25 years of experience, a two-page resume is almost always the right choice. Executives are evaluated on their most recent 10–15 years. Anything older is context, not evidence.' },
      { type: 'p', text: 'The exception: academic CVs, federal government resumes, and some highly technical research roles where a longer format is expected. In those cases, follow the conventions of your field.' },
      { type: 'h2', text: 'Length isn\'t your real problem' },
      { type: 'p', text: 'After reviewing thousands of job applications, the most common issue isn\'t length — it\'s that resumes read like job descriptions instead of accomplishment stories. A one-page resume full of achievements beats a two-page resume full of duties every time.' },
    ],
  },
  {
    slug: 'internship-resume-guide',
    tag: 'Job Search Tips', tagColor: '#0C63E3', tagBg: '#EEF4FF',
    title: 'Internship Resume Guide: How to Write One That Lands You Interviews',
    excerpt: 'Learn how to write an internship resume that stands out. Includes examples, templates, and tips from recruiters.',
    author: 'Sarah Johnson', authorInitials: 'SJ',
    date: 'Mar 15, 2026', read: '8 min',
    image: 'https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: false,
    body: [
      { type: 'p', text: 'The hardest resume to write is your first one. You don\'t have years of experience to point to, and every piece of advice assumes you do. But internship recruiters know exactly what they\'re looking for — and it\'s not a decorated career history.' },
      { type: 'h2', text: 'What internship recruiters actually care about' },
      { type: 'p', text: 'Internship hiring managers are not looking for experience. They\'re looking for signals of future potential: intellectual curiosity, relevant skills, a track record of initiative, and a demonstrated interest in the field. Your resume needs to tell that story.' },
      { type: 'callout', text: 'Insight from a Google recruiter: "I care more about the project you built over a weekend than the class you took for a grade."' },
      { type: 'h2', text: 'Lead with a skills summary, not an objective statement' },
      { type: 'p', text: 'Objective statements ("Seeking a challenging internship opportunity...") are outdated and say nothing. Replace it with a 2–3 line skills summary that highlights your strongest relevant capabilities and what you\'re excited to bring to a team.' },
      { type: 'h2', text: 'Include every relevant project, even personal ones' },
      { type: 'p', text: 'That app you built. The research paper you\'re proud of. The club you helped grow. The freelance work you did for a neighbor. All of it is fair game. For an internship resume, personal projects and coursework often carry more weight than a generic part-time job.' },
      { type: 'h2', text: 'Add a video pitch and stand out immediately' },
      { type: 'p', text: 'Most internship applicants are at a similar experience level. A video pitch is the fastest way to communicate what a resume can\'t: your energy, communication skills, and genuine enthusiasm for the role. Students who add a Reslink to their internship applications report significantly higher response rates.' },
    ],
  },
  {
    slug: 'showcase-soft-skills',
    tag: 'Job Search Tips', tagColor: '#0C63E3', tagBg: '#EEF4FF',
    title: 'How to Showcase Soft Skills on Your Resume (With Real Examples)',
    excerpt: 'Learn the top soft skills for resumes, how to showcase them effectively, and why employers care more than ever.',
    author: 'Michael Chen', authorInitials: 'MC',
    date: 'Mar 12, 2026', read: '5 min',
    image: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/3182812/pexels-photo-3182812.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: true,
    body: [
      { type: 'p', text: '"Excellent communicator." "Strong team player." "Results-driven professional." These phrases appear on millions of resumes and mean absolutely nothing. Listing soft skills is easy. Proving them is hard. Here\'s how to actually do it.' },
      { type: 'h2', text: 'The rule: never claim, always demonstrate' },
      { type: 'p', text: 'Any hiring manager who reads "strong communicator" on a resume rolls their eyes. Anyone can write that. What they can\'t fake is a specific story: "Led weekly cross-functional syncs between product, engineering, and sales to align on sprint priorities — reduced miscommunication-related delays by 40%." That proves communication.' },
      { type: 'callout', text: 'The STAR method (Situation, Task, Action, Result) is your best tool for turning claimed soft skills into proven ones.' },
      { type: 'h2', text: 'Leadership without the title' },
      { type: 'p', text: 'You don\'t need to be a manager to demonstrate leadership on your resume. Did you mentor a new hire? Spearhead a process change? Volunteer to lead a project when no one else would? These are leadership signals — and they\'re more credible than a job title.' },
      { type: 'h2', text: 'The soft skill that a video resume proves instantly' },
      { type: 'p', text: 'Communication is the most in-demand soft skill across virtually every industry. And it\'s also the hardest to prove in text. A 90-second video pitch does what no resume bullet point ever can — it shows a hiring manager exactly how you present yourself, how you structure your thoughts, and whether you\'re the kind of person they\'d enjoy working with.' },
    ],
  },
  {
    slug: 'best-video-resume-tools',
    tag: 'Video Resume Tips', tagColor: '#7C3AED', tagBg: '#F3EEFF',
    title: 'The Best Video Resume Tools for Job Seekers (2026 Edition)',
    excerpt: 'Discover the best video resume tools in 2026 — including Loom.com, VEED.IO, and Reslink. Learn how to choose.',
    author: 'Roxanne Taku', authorInitials: 'RT',
    date: 'Mar 10, 2026', read: '5 min',
    image: 'https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/3861958/pexels-photo-3861958.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: false,
    body: [
      { type: 'p', text: 'Video resumes have gone from a novelty to a genuine competitive advantage. But not all tools are built the same — and using the wrong one can actually hurt your chances. Here\'s a breakdown of the top options in 2026 and when to use each.' },
      { type: 'h2', text: 'Loom — great for async communication, not ideal for job seeking' },
      { type: 'p', text: 'Loom is a fantastic tool for recording and sharing screen content, and it\'s widely used in remote teams. But it\'s not built for job seekers. Your video will live on a generic Loom page with no profile context, no resume integration, and no analytics beyond basic view counts.' },
      { type: 'h2', text: 'VEED.IO — strong editing, but no candidate-specific features' },
      { type: 'p', text: 'VEED.IO is a solid video editing platform with good subtitling and captioning tools. If you want to produce a polished, edited video resume, it\'s a reasonable option. The downside: it\'s not designed for hiring workflows, so you\'ll be sharing a raw video link without a professional profile or recruiter analytics.' },
      { type: 'callout', text: 'The key question: Does the tool make it easy for a recruiter to consume your profile quickly? If your video lives on a generic page with no context, you\'re making their job harder.' },
      { type: 'h2', text: 'Reslink — purpose-built for job seekers' },
      { type: 'p', text: 'Reslink combines your video pitch, resume highlights, and real-time analytics in a single shareable profile. PitchAI generates your script from your resume, the built-in teleprompter keeps you on track while recording, and you can see exactly when a recruiter views you and how long they watched.' },
      { type: 'p', text: 'For job seekers who want a professional, recruiter-optimized experience, Reslink is the tool built specifically for this use case.' },
    ],
  },
  {
    slug: 'do-video-resumes-work',
    tag: 'Video Resume Tips', tagColor: '#7C3AED', tagBg: '#F3EEFF',
    title: 'Do Video Resumes Really Increase Your Chances of Getting an Interview?',
    excerpt: 'Can a video resume help you land more interviews? See the data, psychology, and best practices behind the trend.',
    author: 'Sarah Johnson', authorInitials: 'SJ',
    date: 'Mar 8, 2026', read: '5 min',
    image: 'https://images.pexels.com/photos/4050291/pexels-photo-4050291.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/4050291/pexels-photo-4050291.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: true,
    body: [
      { type: 'p', text: 'The short answer is yes — but with important caveats. A video resume can dramatically increase your callback rate, but a bad one can hurt your chances more than no video at all. Here\'s what the data says, and what it means for you.' },
      { type: 'h2', text: 'What the research actually shows' },
      { type: 'p', text: 'Multiple studies from recruiting analytics platforms show that candidates who include a video profile in their application receive 2–3× more recruiter responses than those who don\'t, across industries ranging from finance to software to operations.' },
      { type: 'p', text: 'The psychology is straightforward: humans are wired to respond to faces and voices. A recruiter who watches your 90-second pitch has already formed a relationship with you before the first call — and that relationship is built on actual presence, not keywords.' },
      { type: 'callout', text: 'The average recruiter spends 7 seconds scanning a resume. The average recruiter watches 85% of a 90-second video pitch. That\'s a 10× engagement difference.' },
      { type: 'h2', text: 'When video resumes don\'t work' },
      { type: 'p', text: 'A poorly lit, awkward, or disorganized video will do damage. If you look uncomfortable, if your audio is bad, or if your script sounds like you\'re reading a grocery list, you\'ve created a negative first impression that\'s worse than no impression at all.' },
      { type: 'p', text: 'The solution isn\'t perfection — it\'s preparation. A clear script, decent lighting, a quiet room, and two or three practice takes are all you need. The goal isn\'t a film production. It\'s a confident conversation.' },
      { type: 'h2', text: 'The winning combination' },
      { type: 'p', text: 'The highest callback rates come from candidates who pair a strong PDF resume with a polished video pitch that links directly from their application. The PDF gets through the ATS. The video gets the callback.' },
    ],
  },
  {
    slug: 'resume-mistakes',
    tag: 'Job Search Tips', tagColor: '#0C63E3', tagBg: '#EEF4FF',
    title: '10 Resume Mistakes That Are Costing You Interviews',
    excerpt: 'Avoid these common resume mistakes that hiring managers see every day. Learn what to fix and how to fix it fast.',
    author: 'Roxanne Taku', authorInitials: 'RT',
    date: 'Mar 5, 2026', read: '6 min',
    image: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: false,
    body: [
      { type: 'p', text: 'We\'ve reviewed thousands of resumes. The same mistakes appear over and over — and they\'re costing talented candidates interviews they deserve. Here are the ten most common, and exactly how to fix each one.' },
      { type: 'h2', text: '1. Duties instead of achievements' },
      { type: 'p', text: '"Responsible for managing social media accounts" tells me what your job description said. "Grew Instagram following from 12K to 84K in eight months through a weekly long-form content strategy" tells me what you actually did. Every bullet should be an achievement.' },
      { type: 'h2', text: '2. A generic objective statement' },
      { type: 'p', text: 'Objective statements that say "seeking a challenging role where I can apply my skills" are filler. Replace it with a concise professional summary that highlights your strongest 2–3 selling points relevant to this specific role.' },
      { type: 'callout', text: 'Quick fix: Search "professional summary [your job title] examples" and rewrite yours from scratch in 10 minutes.' },
      { type: 'h2', text: '3. Missing keywords' },
      { type: 'p', text: 'Most large companies use ATS software that screens resumes before a human sees them. If your resume doesn\'t contain the exact keywords from the job description, it gets filtered out automatically. Mirror the language in the posting.' },
      { type: 'h2', text: '4. Inconsistent formatting' },
      { type: 'p', text: 'Mixing fonts, inconsistent date formats, and random indentation all signal a lack of attention to detail — one of the most important traits in virtually any role. Pick a format and apply it consistently across every entry.' },
      { type: 'h2', text: '5–10: The rest of the list' },
      { type: 'p', text: 'Not quantifying your impact. Including irrelevant experience. Using a personal email that looks unprofessional. Listing references on the resume itself. Using a generic file name. Not tailoring it to the specific role. Each of these is a small thing — but small things accumulate.' },
    ],
  },
  {
    slug: 'create-video-resume',
    tag: 'Video Resume Tips', tagColor: '#7C3AED', tagBg: '#F3EEFF',
    title: 'How to Create a Video Resume That Actually Gets You Hired',
    excerpt: 'Step-by-step guide to creating a video resume that hiring managers love. Includes scripts, tips, and examples.',
    author: 'Michael Chen', authorInitials: 'MC',
    date: 'Mar 3, 2026', read: '10 min',
    image: 'https://images.pexels.com/photos/3823488/pexels-photo-3823488.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/3823488/pexels-photo-3823488.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: false,
    body: [
      { type: 'p', text: 'A video resume that works isn\'t about production quality. It\'s about being the kind of person a hiring manager wants to meet. Here\'s a step-by-step process for creating one that does exactly that.' },
      { type: 'h2', text: 'Step 1: Write your script first' },
      { type: 'p', text: 'Never record without a script. Improvised video resumes ramble, lose their point, and make you look unprepared — the exact opposite of what you want. Write out every word, read it aloud, time it, and edit until it\'s under 90 seconds.' },
      { type: 'callout', text: 'The formula: Who you are (10 sec) → What you\'ve done (30 sec) → What you\'re great at (20 sec) → Why this role/company (20 sec) → Call to action (10 sec)' },
      { type: 'h2', text: 'Step 2: Set up your environment' },
      { type: 'p', text: 'You don\'t need a studio. You need: a window providing natural side light, a clean or blurred background, and a quiet room. That\'s it. Your laptop camera or phone camera is good enough. The single biggest technical upgrade you can make is improving your audio — a $30 clip-on microphone makes a meaningful difference.' },
      { type: 'h2', text: 'Step 3: Use a teleprompter' },
      { type: 'p', text: 'Memorizing a 90-second script is stressful and rarely sounds natural. A teleprompter lets you read your script at eye level while looking directly at the camera. The result is confident, prepared delivery without the robotic quality of obvious memorization.' },
      { type: 'h2', text: 'Step 4: Record until it feels natural' },
      { type: 'p', text: 'Most people need 5–10 takes before they get one they\'re happy with. This is normal. Don\'t settle for the first take. Don\'t spend three hours perfecting it either. When you watch it back and think "I\'d be happy to send this" — stop.' },
      { type: 'h2', text: 'Step 5: Pair it with your resume in one link' },
      { type: 'p', text: 'A video file attached to an email is not a video resume. It\'s an inconvenience. Your video needs to live alongside your resume highlights in a professional, shareable profile — so a recruiter can get the full picture in one click from any device.' },
    ],
  },
  {
    slug: 'analytics-dashboard',
    tag: 'Product Updates', tagColor: '#059669', tagBg: '#ECFDF5',
    title: 'Product Update: Introducing Analytics Dashboard 2.0',
    excerpt: 'Get deeper insights into your Reslink performance with our new analytics dashboard. See what\'s new.',
    author: 'Dominic Giacona', authorInitials: 'DG',
    date: 'Mar 1, 2026', read: '4 min',
    image: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=900&h=500&fit=crop',
    imageFull: 'https://images.pexels.com/photos/590022/pexels-photo-590022.jpeg?auto=compress&cs=tinysrgb&w=1400&h=700&fit=crop',
    hot: false,
    body: [
      { type: 'p', text: 'Today we\'re shipping Analytics Dashboard 2.0 — a complete rebuild of how you understand who\'s looking at your Reslink and what they\'re doing with it. Here\'s everything that\'s new.' },
      { type: 'h2', text: 'Per-viewer engagement data' },
      { type: 'p', text: 'Previously, your analytics showed aggregate view counts and total watch time. Now you can see each individual viewer: when they viewed your profile, how long they watched your video, whether they downloaded your resume, and whether they returned for a second look.' },
      { type: 'callout', text: 'If a recruiter at a company you applied to views your profile three times in two days — that\'s a signal to follow up. Now you\'ll know.' },
      { type: 'h2', text: 'Geographic and device insights' },
      { type: 'p', text: 'Know whether your profile is being viewed from mobile or desktop, and which cities or countries your viewers are in. This is particularly useful for candidates targeting specific markets or remote-first companies.' },
      { type: 'h2', text: 'Engagement funnel' },
      { type: 'p', text: 'The new funnel view shows you: how many people clicked your link, how many started your video, how many watched more than 50%, and how many downloaded your resume. This helps you identify exactly where to improve — whether that\'s your thumbnail, your opening line, or your resume itself.' },
      { type: 'h2', text: 'Available now' },
      { type: 'p', text: 'Analytics Dashboard 2.0 is live for all Pro and Premium users starting today. Free users can see aggregate view counts. If you\'re not yet on a paid plan, now is a great time to upgrade.' },
    ],
  },
];
